In [ ]:
# RANDOM DECISION FOREST ALGORITHMS

In [ ]:
# Application fo Random Decision Forest
# 1. Remote Sensing - Used in ETM devices to acquire images of the earth's surface
# 2. Object Detection - Multiclass object detection is done using RFA
# 3. Kinect _ Track biy movements and recreate it in the game

In [ ]:
# WHY RDF
# 1. No overfitting - Use multipletrees reduce the risk of overfitting
# 2. High accuracy - Runs efficiently on large database
# 3. Estimates Missing Data - Can maintain accuracy when a large proportion of data is missing 

In [ ]:
# What is RDF
# Is a method that operates by constructing multiple Decision Trees during traning phase.
# The Decision of the majority of the trees is choosen by the random forest as the final decision

In [ ]:
# Decision Tree
# IS a tree shape diagram used to determine a course of action. Each branch of the tree represents a possible decision , occurrence or reaction

In [ ]:
# STATEMENT

In [ ]:
# What species of Iris do these flowers belong to ?

In [2]:
# Loading the library with the iris dataset
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# import RFC 
from sklearn.ensemble import RandomForestClassifier
# setting random seed
np.random.seed(0)

In [ ]:
# Explorring the dataset

In [3]:
# Create an object called iris with the iris data
iris = load_iris()

In [4]:
# Creating a dataframe with the four feature variable
df = pd.DataFrame(iris.data, columns= iris.feature_names)

In [5]:
# Viewing the top 5 row
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
# dding a new column for the species name
df['species'] =pd.Categorical.from_codes(iris.target, iris.target_names)

In [10]:
# Viewing the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [11]:
# Viewing the last 5 rows
df.tail()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica

In [17]:
# Create Test and Trainig data
df['is_train'] = np.random.uniform(0 ,1 , len(df))<= .70
# View the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa     False  
2  setosa      True  
3  setosa      True  
4  setosa     False

In [18]:
# Create dataframes with Test rows and Training rows
train , test = df[df['is_train']== True], df[df['is_train'] == False]

In [19]:
# Show the number of observations for the test and training dataframes
print("Number of observation in the Training data:: ", len(train))
print("Number of observation in the Test data:: ", len(test))

Number of observation in the Training data::  107
Number of observation in the Test data::  43


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  is_train  
0       setosa      True  
1       setosa     False  
2       setosa      True  
3       setosa      True  
4       setosa     False  
..         ...       ...  
145  virginica     False  
146  virginica      True  
147  virginica      True  
148  virginica      True  
149  virginica     False  

[150 rows x 6 columns]

In [27]:
# Create a list of the feature column's names
features = df.columns[:4]
# View features
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [28]:
# Converting each species name into digits
y = pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
      dtype=int64)

In [29]:
# Creating a random forest classifier
clf = RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(train[features], y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [30]:
# Applying the trained classifier to the test
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2],
      dtype=int64)

In [31]:
# Viewing the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[0:10]

array([[0.97, 0.03, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.98, 0.02, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.98, 0.02, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.97, 0.03, 0.  ]])

In [32]:
# Mapping n ames for the plants for each predicted plant class
preds = iris.target_names[clf.predict(test[features])]

In [34]:
# View the PREDICTED species for the first five observation
preds[:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [35]:
# Viewing the ACTUAL species for first five observations
test['species'].head()

1     setosa
4     setosa
8     setosa
9     setosa
13    setosa
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [38]:
# Creating confusion matrix
pd.crosstab(test['species'],preds, rownames=['Actual Species'], colnames=['Predicted Species'])

Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 15           0          0
versicolor              0          10          1
virginica               0           1         16

In [50]:
preds = iris.target_names[clf.predict([[3.5,4,2.3,5],[6.3,4,1,1],[5.0,3.6,1.4,2.0]])]

In [51]:
preds

array(['setosa', 'setosa', 'setosa'], dtype='<U10')